spring:
  datasource:
    username: postgres
    password: docker
    platform: postgres
    url: jdbc:postgresql://localhost:5432/spring_cloud_transportador
  jpa:
    hibernate:
      ddl-auto: update