server:
  port: 8888
  
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wagnerww/Netflix-OSS-example
          search-paths: microservice-repo
          